apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lmp-mirrors
  namespace: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: standard-rwo

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: mirror-lmp
  namespace: data

spec:
  schedule: 3 */4 * * *
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            infra.foundries.io/gke-nodepool: data
          restartPolicy: Never
          containers:
            - name: mirror-lmp
              image: ghcr.io/lmp-mirrors/mirror-lmp:main
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /mirrors
                  name: lmp-mirrors
          volumes:
            - name: lmp-mirrors
              persistentVolumeClaim:
                claimName: lmp-mirrors
